# Generated by Django 5.0.3 on 2024-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninea', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(default='company_logo/default.png', upload_to='company_logo')),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('legal_form', models.CharField(choices=[('SA', 'S.A'), ('SARL', 'S.A.R.L'), ('GIE', 'G.I.E'), ('SNC', 'S.N.C'), ('SUARL', 'S.U.A.R.L')], max_length=5)),
                ('phone', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
