# Generated by Django 5.0.3 on 2024-03-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(default='job_images/default.png', upload_to='job_images/')),
                ('state', models.CharField(choices=[('D', 'Brouillon'), ('P', 'En cours'), ('C', 'Clôturé')], max_length=1)),
                ('close_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
